language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js: stable
cache:
  yarn: true
branches:
  except:
    - /^v\d/
install:
  - yarn global add polymer-cli
  - yarn global add bower
  - yarn install
  - bower install
before_script:
  - yarn run lint
script:
  - echo "The test task is disabled."
  - xvfb-run yarn run test
  - xvfb-run polymer test
after_success:
  - yarn run build
